version: '3.3'
services:

#proxy
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped #ensure survives crashes
    ports:
      - '80:80'
      - '81:81' #admin panel
      - '443:443'
    volumes:
      - ./proxy/data:/data
      - ./proxy/letsencrypt:/etc/letsencrypt
      - ./proxy/config.json:/app/config/production.json #config database

#vpn
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Mendoza
      - SERVERURL=1.1.1.1 #optional [YOUR_SERVER_IP]
      - SERVERPORT=51820 #optional
      - PEERS=7 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.11.12.0 #optional
    volumes:
      - /root/wireguard:/config
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

#web
  www:
    image: nginx
    restart: unless-stopped
    expose:
    - '8080'
    volumes:
    - ./web/public_html:/usr/share/nginx/html

#db
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    expose:
      - '3306'
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=changeMe
      - MYSQL_USER=changeMe
      - MYSQL_PASSWORD=changeMe
      - MYSQL_ROOT_PASSWORD=changeMe

